Fixed loading the C-extensions on Python 3.8 -- by :user:`bdraco`.
